/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Image;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import model.Bicicleta;
import model.Persona;
import connection.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import model.GenerarInforme;

/**
 *
 * @author ASUS
 */
public class Prestar extends javax.swing.JFrame {
    ArrayList<Bicicleta> bicicletasEnEstacion = new ArrayList<>();
    /**
     * Creates new form Prestar
     */
    public Prestar() {
        initComponents();
        ImageIcon logo = new ImageIcon("src/main/java/img/LogoE.png");
        Icon iconologo = new ImageIcon(logo.getImage().getScaledInstance(lbl_logo.getWidth(), lbl_logo.getHeight(), Image.SCALE_SMOOTH));
        lbl_logo.setIcon(iconologo);
        this.repaint();
        ImageIcon usuario = new ImageIcon("src/main/java/img/encicla.jpg");
        Icon iconouser = new ImageIcon(usuario.getImage().getScaledInstance(lbl_user.getWidth(), lbl_user.getHeight(), Image.SCALE_SMOOTH));
        lbl_user.setIcon(iconouser);   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_logo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbl_user = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmb_estacion = new javax.swing.JComboBox<>();
        btn_prestar = new javax.swing.JButton();
        btn_entregar = new javax.swing.JButton();
        btn_informe = new javax.swing.JButton();
        btn_regresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ENCICLA");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("@UdeA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel2)))
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(lbl_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(31, 31, 31))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Seleccione su estación");

        cmb_estacion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmb_estacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ruta N", "Campus Nacional", "Suramericana", "La 65", "UPB" }));

        btn_prestar.setText("Prestar");
        btn_prestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prestarActionPerformed(evt);
            }
        });

        btn_entregar.setText("Entregar");
        btn_entregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_entregarActionPerformed(evt);
            }
        });

        btn_informe.setText("Generar Informe");
        btn_informe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_informeActionPerformed(evt);
            }
        });

        btn_regresar.setText("Regresar");
        btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_prestar)
                            .addComponent(btn_entregar)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(lbl_user, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(cmb_estacion, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(btn_informe))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(btn_regresar)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_user, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmb_estacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btn_prestar)
                .addGap(18, 18, 18)
                .addComponent(btn_entregar)
                .addGap(18, 18, 18)
                .addComponent(btn_informe)
                .addGap(18, 18, 18)
                .addComponent(btn_regresar)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_prestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prestarActionPerformed
    obtenerBicicletas(cmb_estacion.getSelectedItem().toString());
    }//GEN-LAST:event_btn_prestarActionPerformed

    private void btn_entregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_entregarActionPerformed
     String estacionSeleccionada = cmb_estacion.getSelectedItem().toString();
    Bicicleta bicicletaADevolver = obtenerBicicletaParaEntregar(estacionSeleccionada);
    if (bicicletaADevolver != null) {
        // Devolver la bicicleta a la base de datos
        devolverBicicletaABaseDeDatos(bicicletaADevolver);
        // Eliminar la bicicleta del ArrayList
        bicicletasEnEstacion.remove(bicicletaADevolver);
        // Asignar NULL a la persona que tiene la bicicleta
        bicicletaADevolver.setPerson(null);
        // Actualizar la interfaz gráfica u otras operaciones
    } else {
        // Manejar el caso en el que no hay bicicletas para devolver
        System.out.println("No hay bicicletas para devolver en la estación seleccionada.");
    }
    }//GEN-LAST:event_btn_entregarActionPerformed

    private void btn_informeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_informeActionPerformed
      GenerarInforme.crearInforme(bicicletasEnEstacion);
    }//GEN-LAST:event_btn_informeActionPerformed

    private void btn_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresarActionPerformed
       this.dispose();
       new Login().setVisible(true);
    }//GEN-LAST:event_btn_regresarActionPerformed
    // Método para devolver la bicicleta a la base de datos
private void devolverBicicletaABaseDeDatos(Bicicleta bicicleta) {
    Connection conn = null;
    PreparedStatement ps = null;
    Conexion conexion = null;
    try {
        conn = conexion.getConexion();
        String query = "INSERT INTO bicicletas (color, numero, estacion) VALUES (?, ?, ?)";
        ps = conn.prepareStatement(query);
        ps.setString(1, bicicleta.getColor());
        ps.setInt(2, bicicleta.getNumero());
        ps.setString(3, bicicleta.getEstacion());
        ps.executeUpdate();
    } catch (SQLException e) {
        e.printStackTrace();
    } finally {
        try {
            // Cerrar recursos
            if (ps != null) ps.close();
            if (conn != null) conn.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}

    private Bicicleta obtenerBicicletaParaEntregar(String estacionSeleccionada) {
    // Implementa la lógica para obtener la bicicleta que se va a devolver en la estación seleccionada
    for (Bicicleta bicicleta : bicicletasEnEstacion) {
        if (bicicleta.getEstacion().equals(estacionSeleccionada)) {
            return bicicleta;
        }
    }
    return null;
}
        
     public ArrayList<Bicicleta> obtenerBicicletas(String estacionSeleccionada) {
        PreparedStatement ps = null;
        ResultSet rs = null;
        PreparedStatement ps2 = null;
        ResultSet rs2 = null;

        try (Connection conn = Conexion.getConexion()) {
            String query = "SELECT * FROM bicicletas WHERE estacion = ?";
            String query2 = "SELECT * FROM personas LIMIT 1"; // Obtener la primera persona
            ps = conn.prepareStatement(query);
            ps.setString(1, estacionSeleccionada);
            rs = ps.executeQuery();

            if (rs.next()) {
                Bicicleta bicicleta = new Bicicleta();
                bicicleta.setColor(rs.getString("color"));
                bicicleta.setNumero(rs.getInt("numero"));

                // Obtener la información de la primera persona
                ps2 = conn.prepareStatement(query2);
                rs2 = ps2.executeQuery();

                if (rs2.next()) {
                    Persona persona = new Persona();
                    persona.setNombre(rs2.getString("nombre")+" "+rs2.getString("apellido"));
                    bicicleta.setPerson(persona);
                }

                bicicleta.setEstacion(estacionSeleccionada);
                bicicletasEnEstacion.add(bicicleta);
                eliminarBicicleta(rs.getInt("numero"));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        } return bicicletasEnEstacion;
     } 
     
     private void eliminarBicicleta(int numBicicleta) {
    PreparedStatement ps = null;

    try (Connection conn = Conexion.getConexion()) {
        String query = "DELETE FROM bicicletas WHERE numero = ?";
        ps = conn.prepareStatement(query);
        ps.setInt(1, numBicicleta);
        ps.executeUpdate();
    } catch (SQLException e) {
        e.printStackTrace();
    } finally {
        try (Connection conn = Conexion.getConexion()) {
            // Cerrar recursos
            if (ps != null) ps.close();
            if (conn != null) conn.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prestar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prestar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prestar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prestar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prestar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_entregar;
    private javax.swing.JButton btn_informe;
    private javax.swing.JButton btn_prestar;
    private javax.swing.JButton btn_regresar;
    private javax.swing.JComboBox<String> cmb_estacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JLabel lbl_user;
    // End of variables declaration//GEN-END:variables
}
